# Read the data from all tables.
select * from customer;
select * from supplier;
select * from product;
select * from orderitem;
select * from orders;
# Find the country-wise count of customers.
select country, count(firstname) from customer group by country;

#Display the products which are not discontinued.
select * from product where Isdiscontinued=0;

#Display the list of companies along with the product name that they are supplying.

select s.companyname, p.productname from supplier s join product p on s.id=p.supplierid;

#Display customer information about who stays in 'Mexico'

select * from customer where country='MEXICO';

#Display the costliest item that is ordered by the customer.

select * from product;
select max(unitprice) from product;
select max(unitprice) from orderitem;

select * from orderitem order by unitprice desc limit 1;

#Display supplier id who owns the highest number of products.
select supplierid, count(*) from supplier s join product p on s.id= p.supplierid
group by supplierid
order by count(*) desc
limit 1;


select supplierid, count(*) from product
group by supplierid
order by count(*) desc
limit 5;

#Display month-wise and year-wise counts of the orders placed.

select year(orderdate), monthname(orderdate), count(*) from orders group by year(orderdate), monthname(orderdate);

#Which country has the maximum number of suppliers?

select country, count(*) from supplier group by country order by count(*) desc;

#Which customers did not place any orders.
select * from customer c left join orders o on c.id=o.customerid where o.customerid is null;

select * from customer where id not in
(select customerid from orders);

select * from orders;
#Section B --> Know the business 			Time: 60 min.

#Arrange the product id, product name based on high demand by the customer.

select o.Productid, p.productname, sum(quantity) from orderitem o join product p on o.productid=p.id 
group by o.Productid, p.productname
order by sum(quantity) desc;

select o.Productid, p.productname, count(*) from orderitem o join product p on o.productid=p.id 
group by O.productid, p.productname
order by count(*) desc
limit 1;
#(This approach shows How many times the product has been ordered)

#Display the number of orders delivered every year.

select year(orderdate), count(*) from orders
group by year(orderdate);

#Calculate year-wise total revenue.
select * from orders;
select Year(orderdate), sum(TotalAmount) from orders
group by year(orderdate);

select year(o.orderdate), sum(i.unitprice*i.quantity) revenue from orders o join orderitem i on o.id=i.orderid
group by year(o.orderdate);

#Display the customer details whose order amount is maximum including his past orders.
select c.id, c.firstname, c.lastname, sum(Totalamount) from customer c join orders o on c.id=o.customerid
group by o.customerid
order by sum(TotalAmount) desc
limit 1;

# 2nd table doesnt have firstname lastname so putting o.customer id makes the query simple and less messy

#Display total amount ordered by each customer from high to low.
select c.*, customerid, sum(totalamount) from orders o join customer c on o.customerid=c.id
group by customerid
order by sum(totalamount) desc;

# sales and marketing department of this company wants to find out how frequently customer have business with them. (Answer Q 6 for the same)
#Approach - List the current and previous order dates for each customers.

# Do it with windows function lag

#Find out top 3 suppliers in terms of revenue generated by their products.
select * from supplier; # supplier name
select * from product; # product name, supplier id, product id
select * from orderitem; # revenue productid

select s.companyname,s.contactname, supplierid, sum(o.unitprice*o.quantity) revenue
from supplier s join product p on s.id=p.supplierid join orderitem o on p.id=o.productid
group by supplierid
order by revenue desc
limit 3;

#Display latest order date (should not be same as first order date) of all the customers with customer details.

select c.*, customerid, max(orderdate), count(orderdate) from orders o join  customer c on c.id=o.customerid
group by customerid
having count(orderdate)>1;

#Display the product name and supplier name for each order

select o.orderid, p.productname, s.companyname from orderitem o join product p on o.productid=p.id 
join supplier s on p.supplierid=s.id
order by o.orderid;

#Section C --> Business Analysis 			Time: 60 min.

#Fetch the records to display the customer details who ordered more than 10 product quantity in the single order

select * from orderitem;

select c.id, concat(c.firstname, c.lastname) as Fullname, sum(i.quantity) as TotalQty from 
customer c join orders o on c.id=o.customerid
join orderitem i on o.id=i.orderid
group by O.ID, fullname, c.id
having TotalQty>10;

#Display all the product details with the ordered quantity size as 1.

select P.*, quantity from product p join orderitem o on p.id=o.productid where quantity=1;

#Display the compan(y)ies which supplies products whose cost is above 100.
select s.companyname, p.id from supplier s join product p on s.id=p.supplierid
where unitprice>100;

#Create a combined list to display customers and supplier list as per the below format.

select 'customer' as Type , concat(firstname, ' ', lastname) as ContactName, city, country, phone from customer
union
select 'supplier', contactname, city, country, phone from supplier;

#Section D --> Challenge 					Time:60 Min.

#Company sells the product at different discounted rates. Refer actual product price in product table and 
#selling price in the order item table. Write a query to find out total amount saved in each order then display the orders from highest to lowest amount saved.

select o.orderid, o. productid, sum((p.unitprice * o.quantity) - (o.unitprice*o.quantity)) total_amount_saved
from product p join orderitem o on p.id=o.productid
group by o.productid, o.orderid
order by total_amount_saved desc;

#Mr. Kavin want to become a supplier. He got the database of "Richard's Supply" for reference. Help him to pick: 
#a. List few products that he should choose based on demand.
#b. Who will be the competitors for him for the products suggested in above questions.

select p.*, o.id, o.unitprice*o.quantity as revenue from orderitem o join product p 
on p.id=o.productid
order by revenue desc;

select * from orderitem;

select productname from product p join (
select productid,count(id) from orderitem
group by productid 
order by count(id) desc) t
on p.id=t.productid;

select s.companyname, productname from supplier s join 
(select productname from product p join (
select p.supplierid, productid,count(id) from orderitem
group by p.productid , p.supplierid
order by count(id) desc) t
on p.id=t.productid
limit 10) tt
on s.id=tt.supplierid;

select s.contactname, p.*, o.id, o.unitprice*o.quantity as revenue 
from orderitem o join product p on p.id=o.productid
join supplier s on s.id=p.supplierid
order by revenue desc;

select productid,productname,contactname,count(ProductId) cp  from orderitem ot join product p on ot.productid=p.id 
join supplier s  on p.supplierid=s.id group by 1 order by cp desc ;

#Every supplier supplies specific products to the customers. Create a view of suppliers and total sales made by their products and write a query on this view to find out top 2 suppliers (using windows function RANK() in each country by total sales done by the products.
-- Do it tomorrow using windows function

#Find out for which products, UK is dependent on other countries for the supply.
#List the countries which are supplying these products in the same list.


